//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPathCodeVisualization.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int AvtivityLv5 {
            get {
                return ((int)(this["AvtivityLv5"]));
            }
            set {
                this["AvtivityLv5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int AvtivityLv4 {
            get {
                return ((int)(this["AvtivityLv4"]));
            }
            set {
                this["AvtivityLv4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int AvtivityLv3 {
            get {
                return ((int)(this["AvtivityLv3"]));
            }
            set {
                this["AvtivityLv3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int AvtivityLv2 {
            get {
                return ((int)(this["AvtivityLv2"]));
            }
            set {
                this["AvtivityLv2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int AvtivityLv1 {
            get {
                return ((int)(this["AvtivityLv1"]));
            }
            set {
                this["AvtivityLv1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int VariableLv5 {
            get {
                return ((int)(this["VariableLv5"]));
            }
            set {
                this["VariableLv5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int VariableLv4 {
            get {
                return ((int)(this["VariableLv4"]));
            }
            set {
                this["VariableLv4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int VariableLv3 {
            get {
                return ((int)(this["VariableLv3"]));
            }
            set {
                this["VariableLv3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int VariableLv2 {
            get {
                return ((int)(this["VariableLv2"]));
            }
            set {
                this["VariableLv2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int VariableLv1 {
            get {
                return ((int)(this["VariableLv1"]));
            }
            set {
                this["VariableLv1"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Default_ActivityLv5 {
            get {
                return ((int)(this["Default_ActivityLv5"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int Default_ActivityLv4 {
            get {
                return ((int)(this["Default_ActivityLv4"]));
            }
            set {
                this["Default_ActivityLv4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Default_ActivityLv3 {
            get {
                return ((int)(this["Default_ActivityLv3"]));
            }
            set {
                this["Default_ActivityLv3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int Default_ActivityLv2 {
            get {
                return ((int)(this["Default_ActivityLv2"]));
            }
            set {
                this["Default_ActivityLv2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Default_ActivityLv1 {
            get {
                return ((int)(this["Default_ActivityLv1"]));
            }
            set {
                this["Default_ActivityLv1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Default_VariableLv5 {
            get {
                return ((int)(this["Default_VariableLv5"]));
            }
            set {
                this["Default_VariableLv5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Default_VariableLv4 {
            get {
                return ((int)(this["Default_VariableLv4"]));
            }
            set {
                this["Default_VariableLv4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int Default_VariableLv3 {
            get {
                return ((int)(this["Default_VariableLv3"]));
            }
            set {
                this["Default_VariableLv3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int Default_VariableLv2 {
            get {
                return ((int)(this["Default_VariableLv2"]));
            }
            set {
                this["Default_VariableLv2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int Default_VariableLv1 {
            get {
                return ((int)(this["Default_VariableLv1"]));
            }
            set {
                this["Default_VariableLv1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ComplexityLv5 {
            get {
                return ((int)(this["ComplexityLv5"]));
            }
            set {
                this["ComplexityLv5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int ComplexityLv4 {
            get {
                return ((int)(this["ComplexityLv4"]));
            }
            set {
                this["ComplexityLv4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int ComplexityLv3 {
            get {
                return ((int)(this["ComplexityLv3"]));
            }
            set {
                this["ComplexityLv3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int ComplexityLv2 {
            get {
                return ((int)(this["ComplexityLv2"]));
            }
            set {
                this["ComplexityLv2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ComplexityLv1 {
            get {
                return ((int)(this["ComplexityLv1"]));
            }
            set {
                this["ComplexityLv1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Default_ComplexityLv5 {
            get {
                return ((int)(this["Default_ComplexityLv5"]));
            }
            set {
                this["Default_ComplexityLv5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int Default_ComplexityLv4 {
            get {
                return ((int)(this["Default_ComplexityLv4"]));
            }
            set {
                this["Default_ComplexityLv4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int Default_ComplexityLv3 {
            get {
                return ((int)(this["Default_ComplexityLv3"]));
            }
            set {
                this["Default_ComplexityLv3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int Default_ComplexityLv2 {
            get {
                return ((int)(this["Default_ComplexityLv2"]));
            }
            set {
                this["Default_ComplexityLv2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Default_ComplexityLv1 {
            get {
                return ((int)(this["Default_ComplexityLv1"]));
            }
            set {
                this["Default_ComplexityLv1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int DepthLv5 {
            get {
                return ((int)(this["DepthLv5"]));
            }
            set {
                this["DepthLv5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int DepthLv4 {
            get {
                return ((int)(this["DepthLv4"]));
            }
            set {
                this["DepthLv4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int DepthLv3 {
            get {
                return ((int)(this["DepthLv3"]));
            }
            set {
                this["DepthLv3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int DepthLv2 {
            get {
                return ((int)(this["DepthLv2"]));
            }
            set {
                this["DepthLv2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int DepthLv1 {
            get {
                return ((int)(this["DepthLv1"]));
            }
            set {
                this["DepthLv1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Default_DepthLv5 {
            get {
                return ((int)(this["Default_DepthLv5"]));
            }
            set {
                this["Default_DepthLv5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Default_DepthLv4 {
            get {
                return ((int)(this["Default_DepthLv4"]));
            }
            set {
                this["Default_DepthLv4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int Default_DepthLv3 {
            get {
                return ((int)(this["Default_DepthLv3"]));
            }
            set {
                this["Default_DepthLv3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int Default_DepthLv2 {
            get {
                return ((int)(this["Default_DepthLv2"]));
            }
            set {
                this["Default_DepthLv2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int Default_DepthLv1 {
            get {
                return ((int)(this["Default_DepthLv1"]));
            }
            set {
                this["Default_DepthLv1"] = value;
            }
        }
    }
}
